import { OptionPopup } from "option_popup.slint";
import { ColorPalette } from "color_palette.slint";
import { EditorTextInput } from "editor_text_input.slint";

export global MainInputAdapter {
	callback tab-pressed();
}

export component MainInput inherits Rectangle {
    in-out property <string> text;
    out property <int> anchor_position_byte_offset: input.anchor_position_byte_offset;
    out property <int> cursor_position_byte_offset: input.cursor_position_byte_offset;

    callback show-find();
    callback edited <=> input.edited;

    public function set-selection-offsets(start: int, end: int) {
        input.set-selection-offsets(start, end);
    }

    forward-focus: input;

    Flickable {
        viewport-height: input.preferred-height + 8px;

        input := EditorTextInput {
            y: 4px;
            width: parent.width - 8px;
            min-height: root.height - 8px;
            text <=> root.text;
            single-line: false;
            wrap: word-wrap;

            extra-options: ["Find"];
            
            extra-option-chosen(option) => {
                show-find();
            }

            key-pressed(e) => {
                if (e.modifiers.control && (e.text == "f" || e.text == "F")) {
                    show-find();
                    return accept;
                }

                if (e.text == Key.Tab) {
                    MainInputAdapter.tab-pressed();
                    return accept;
                }

                reject
            }
        }
    }
}