import { FindReplace, FindReplaceAdapter } from "find_replace.slint";
import { InlineButton } from "inline_button.slint";
import { NamePrompt } from "name_prompt.slint";
import { DeletePrompt } from "delete_prompt.slint";
import { OptionPopup } from "option_popup.slint";
import { ColorPalette } from "color_palette.slint";
import { MainInput } from "main_input.slint";
import { BorderlessWindow } from "borderless_window.slint";
import { NoteModelAdapter } from "model_adapter.slint";

export { FindReplaceAdapter, ColorPalette, NoteModelAdapter }

export global NoteStoreAdapter {
    pure callback get-text(string) -> string;
    callback set-text(string, string);
    callback set-current(string);
}

export component MainWindow inherits BorderlessWindow {
    in-out property <[string]> note-names;
    out property <string> current-note;
    out property <string> text;
    
    property <bool> delete-enabled;
    property <bool> name-enabled;
    property <bool> find-enabled;

    callback close <=> close-button.clicked;
    callback mouse-move(length, length);
    callback set-current-note(string);
    callback set-text(string);
    callback on-text-changed();
    callback move-window(TextHorizontalAlignment, length, TextVerticalAlignment, length);
    
    public function set-selection-offsets(start: int, end: int) {
        main-input.set-selection-offsets(start, end);
    }
    
    function close-prompts() {
        delete-enabled = false;
        name-enabled = false;
        find-enabled = false;
    }

    set-current-note(note) => {
        current-note = note;
        set-text(NoteStoreAdapter.get-text(note));
        NoteStoreAdapter.set-current(note);
    }

    set-text(new-text) => {
        text = new-text;
        on-text-changed();
    }

    on-text-changed => {
        FindReplaceAdapter.text-edited(text);
        NoteStoreAdapter.set-text(current-note, text);
    }

    move(hoz-pos, dx, vert-pos, dy) => {
        move-window(hoz-pos, dx, vert-pos, dy);
    }

    forward-focus: main-input;

    FocusScope {
        key-pressed(e) => {
            if (e.text == Key.Tab) {
                return reject;
            }

            if (e.text == Key.Escape) {
                close-prompts();
            }

            accept
        }

        VerticalLayout {
            TouchArea {
                moved => {
                    mouse-move(
                        self.mouse-x - self.pressed-x,
                        self.mouse-y - self.pressed-y
                    );
                }

                select-popup := OptionPopup {
                    x: 0;
                    y: note-button.height;
                    main-content: true;

                    groups: [note-names, ["Add new"]];
                    actions: ["Rename", "Delete"];
                    actionable-group-index: 0;
                    
                    option-chosen(chosen-name, group-index) => {
                        if (group-index == 0) {
                            set-current-note(chosen-name);
                        } else {
                            close-prompts();
                            NoteModelAdapter.rename-old-name = "";
                            name-enabled = true;
                        }
                    }

                    action-chosen(action, name) => {
                        close-prompts();

                        if (action == "Rename") {
                            NoteModelAdapter.rename-old-name = name;
                            name-enabled = true;
                        } else if (action == "Delete") {
                            NoteModelAdapter.delete-target = name;
                            delete-enabled = true;
                        }
                    }
                }

                Rectangle {
                    background: ColorPalette.accent;

                    HorizontalLayout {
                        alignment: LayoutAlignment.space-between;

                        note-button := InlineButton {
                            text: current-note + " ▼";
                            text-color: ColorPalette.contrast;

                            clicked => {
                                select-popup.show();
                            }
                        }

                        close-button := InlineButton {
                            text: "🗙";
                            text-color: ColorPalette.contrast;
                            accessible-label: "Close";
                            font-size: 1.15rem;
                            vertical-offset: -3px;
                        }
                    }
                }
            }
            
            if name-enabled: name-prompt := NamePrompt {
                close => {
                    name-enabled = false;
                }
            }

            if delete-enabled: delete-prompt := DeletePrompt {
                close => {
                    delete-enabled = false;
                }
            }
            
            if find-enabled: find-prompt := FindReplace {
                close => {
                    find-enabled = false;
                }
            }
            
            main-input := MainInput {
                text <=> root.text;

                show-find => {
                    close-prompts();
                    find-enabled = true;
                }

                edited => {
                    on-text-changed();
                }
            }
        }
    }
}