import { OptionPopup } from "option_popup.slint";
import { ColorPalette } from "color_palette.slint";
import { EditorTextInput } from "editor_text_input.slint";

export component MainInput inherits Rectangle {
    in-out property <string> text;

    callback show-find();
    callback edited <=> input.edited;

    public function set-selection-offsets(start: int, end: int) {
        input.set-selection-offsets(start, end);
    }

    forward-focus: input;

    FocusScope {
        key-pressed(e) => {
            if (e.text == Key.Tab || e.text == Key.Escape) {
                return reject;
            }

            if (e.modifiers.control && (e.text == "f" || e.text == "F")) {
                show-find();
            }

            accept
        }

        Flickable {
            viewport-height: input.preferred-height + 8px;

            input := EditorTextInput {
                y: 4px;
                width: parent.width - 8px;
                min-height: root.height - 8px;
                text <=> root.text;
                single-line: false;
                wrap: word-wrap;

                extra-options: ["Find"];
                
                extra-option-chosen(option) => {
                    show-find();
                }
            }
        }
    }
}