import { InlineButton } from "inline_button.slint";
import { ColorPalette } from "color_palette.slint";

export component OptionPopup {
    in property <[[string]]> groups: [];
    in property <[string]> actions;
    in property <int> actionable-group-index;
    in property <bool> main-content;
    
    property <length> sub-x;
    property <length> sub-y;
    property <string> sub-option;

    callback option-chosen(string, int);
    callback action-chosen(string, string);

    public function show() {
        popup.show();
    }

    popup := PopupWindow {
        width: main-menu.width;
        height: main-menu.height;
        close-policy: close-on-click-outside;

        main-menu := Rectangle {
            width: self.preferred-width;
            height: self.preferred-height;
            border-width: 1px;

            states [
                main when main-content: {
                    background: ColorPalette.accent;
                    border-color: ColorPalette.accent;
                }
                aux when !main-content: {
                    background: ColorPalette.milder;
                    border-color: ColorPalette.border;
                }
            ]

            VerticalLayout {
                for group[index] in groups: VerticalLayout {
                    if index > 0: Rectangle {
                        width: 100%;
                        height: 1px;
                        background: ColorPalette.border;
                    }

                    for option in group: btn := InlineButton {
                        text: option;

                        states [
                            main when main-content: {
                                text-color: ColorPalette.contrast;
                            }
                            aux when !main-content: {
                                text-color: ColorPalette.opposite;
                            }
                        ]
    
                        clicked => {
                            option-chosen(option, index);
                            popup.close();
                        }
    
                        right-click(mouse-x, mouse-y) => {
                            if (actions.length > 0 && actionable-group-index == index) {
                                sub-x = mouse-x + 4px;
                                sub-y = mouse-y + btn.y + 4px;
                                sub-option = option;
                                sub-menu.show();
                            }
                        }
                    }
                }
            }
        }
    }

    sub-menu := PopupWindow {
        x: sub-x;
        y: sub-y;
        width: item-ctx-content.width;
        height: item-ctx-content.height;
        close-policy: close-on-click;

        item-ctx-content := Rectangle {
            width: self.preferred-width;
            height: self.preferred-height;
            background: ColorPalette.milder;
            border-color: ColorPalette.border;
            border-width: 1px;

            VerticalLayout {
                for action in actions: InlineButton {
                    text: action;
                    text-color: ColorPalette.opposite;

                    clicked => {
                        action-chosen(action, sub-option);
                        // popup.close();
                    }
                }
            }
        }
    }
}