import { InlineButton } from "inline_button.slint";
import { ColorPalette } from "color_palette.slint";

export component OptionPopup {
    in-out property <[string]> options: [];
    in-out property <[string]> extras: [];
    in-out property <[string]> actions: [];

    callback option-chosen(string);
    callback extra-chosen(string);
    callback action-clicked(string, string);

    public function show() {
        popup.show();
    }

    popup := PopupWindow {
        property <bool> show-seconday;

        width: main-content.preferred-width + item-ctx-menu.preferred-width - 1px;
        height: max(main-content.preferred-height, item-ctx-menu.preferred-height);
        close-policy: close-on-click-outside;

        Rectangle {
            width: popup.width;
            height: popup.height;

            TouchArea {       
                clicked() => {
                    popup.close();
                }
            }
        }

        main-content := Rectangle {
            x: 0;
            y: 0;
            width: self.preferred-width;
            height: self.preferred-height;
            background: ColorPalette.milder;
            border-color: ColorPalette.border;
            border-width: 1px;

            VerticalLayout {
                for option in options: btn := InlineButton {
                    text: option;
                    text-color: ColorPalette.opposite;

                    clicked => {
                        option-chosen(option);
                        popup.close();
                    }

                    right-click => {
                        item-ctx-menu.y = btn.y;
                        item-ctx-menu.option = option;
                        show-seconday = true;
                    }
                }

                if extras.length > 0: Rectangle {
                    width: 100%;
                    height: 1px;
                    background: ColorPalette.border;
                }

                for extra in extras: InlineButton {
                    text: extra;
                    text-color: ColorPalette.opposite;

                    clicked => {
                        extra-chosen(extra);
                        popup.close();
                    }
                }
            }
        }

       item-ctx-menu := Rectangle {
            x: main-content.preferred-width - 1px;
            width: self.preferred-width;
            height: self.preferred-height;
            background: ColorPalette.milder;
            border-color: ColorPalette.border;
            border-width: 1px;
            visible: show-seconday;

            property <string> option;

            VerticalLayout {
                for action in actions: InlineButton {
                    text: action;
    
                    clicked => {
                        action-clicked(action, option);
                        popup.close();
                    }
                }
            }
        }
    }
}