import { InlineButton } from "inline_button.slint";
import { ColorPalette } from "color_palette.slint";

export component OptionPopup {
    in property <[[string]]> groups: [];
    in property <[string]> actions;
    in property <int> actionable-group-index;

    callback option-chosen(string, int);
    callback action-chosen(string, string);

    public function show() {
        popup.show();
    }

    popup := PopupWindow {
        property <bool> show-secondary;

        width: main-content.width + item-ctx-menu.width - 1px;
        height: max(main-content.height, item-ctx-menu.height);
        close-policy: close-on-click-outside;

        Rectangle {
            width: popup.width;
            height: popup.height;

            TouchArea {       
                clicked() => {
                    popup.close();
                }
            }
        }

        main-content := Rectangle {
            x: 0;
            y: 0;
            width: self.preferred-width;
            height: self.preferred-height;
            background: ColorPalette.milder;
            border-color: ColorPalette.border;
            border-width: 1px;

            VerticalLayout {
                for group[index] in groups: VerticalLayout {
                    if index > 0: Rectangle {
                        width: 100%;
                        height: 1px;
                        background: ColorPalette.border;
                    }

                    for option in group: btn := InlineButton {
                        text: option;
                        text-color: ColorPalette.opposite;
    
                        clicked => {
                            option-chosen(option, index);
                            popup.close();
                        }
    
                        right-click => {
                            show-secondary = actions.length > 0 && actionable-group-index == index;

                            if (show-secondary) {
                                item-ctx-menu.y = btn.y;
                                item-ctx-menu.option = option;
                                show-secondary = true;
                            }
                        }
                    }
                }
            }
        }

        item-ctx-menu := Rectangle {
            x: main-content.preferred-width - 1px;
            width: self.preferred-width;
            height: self.preferred-height;
            background: ColorPalette.milder;
            border-color: ColorPalette.border;
            border-width: 1px;
            visible: show-secondary;

            property <string> option;

            VerticalLayout {
                for action in actions: InlineButton {
                    text: action;

                    clicked => {
                        action-chosen(action, option);
                        popup.close();
                    }
                }
            }
        }
    }
}